/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReadRouteImport } from './routes/read'
import { Route as TestRouteImport } from './routes/test'
import { Route as ReadIndexRouteImport } from './routes/read.index'
import { Route as ReadChapterIdRouteImport } from './routes/read.$chapterId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ReadChapterIdIndexRouteImport } from './routes/read.$chapterId.index'
import { Route as ReadChapterIdSectionIdRouteImport } from './routes/read.$chapterId.$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIndexRoute = ReadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadRoute,
} as any)
const ReadChapterIdRoute = ReadChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => ReadRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadChapterIdIndexRoute = ReadChapterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadChapterIdRoute,
} as any)
const ReadChapterIdSectionIdRoute = ReadChapterIdSectionIdRouteImport.update({
  id: '/$sectionId',
  path: '/$sectionId',
  getParentRoute: () => ReadChapterIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/read': typeof ReadRouteWithChildren
  '/test': typeof TestRoute
  '/read/$chapterId': typeof ReadChapterIdRouteWithChildren
  '/read/': typeof ReadIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read/$chapterId/$sectionId': typeof ReadChapterIdSectionIdRoute
  '/read/$chapterId/': typeof ReadChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/test': typeof TestRoute
  '/read': typeof ReadIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read/$chapterId/$sectionId': typeof ReadChapterIdSectionIdRoute
  '/read/$chapterId': typeof ReadChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/read': typeof ReadRouteWithChildren
  '/test': typeof TestRoute
  '/read/$chapterId': typeof ReadChapterIdRouteWithChildren
  '/read/': typeof ReadIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read/$chapterId/$sectionId': typeof ReadChapterIdSectionIdRoute
  '/read/$chapterId/': typeof ReadChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/login'
    | '/progress'
    | '/read'
    | '/test'
    | '/read/$chapterId'
    | '/read/'
    | '/api/auth/$'
    | '/read/$chapterId/$sectionId'
    | '/read/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/login'
    | '/progress'
    | '/test'
    | '/read'
    | '/api/auth/$'
    | '/read/$chapterId/$sectionId'
    | '/read/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/login'
    | '/progress'
    | '/read'
    | '/test'
    | '/read/$chapterId'
    | '/read/'
    | '/api/auth/$'
    | '/read/$chapterId/$sectionId'
    | '/read/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  ReadRoute: typeof ReadRouteWithChildren
  TestRoute: typeof TestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/': {
      id: '/read/'
      path: '/'
      fullPath: '/read/'
      preLoaderRoute: typeof ReadIndexRouteImport
      parentRoute: typeof ReadRoute
    }
    '/read/$chapterId': {
      id: '/read/$chapterId'
      path: '/$chapterId'
      fullPath: '/read/$chapterId'
      preLoaderRoute: typeof ReadChapterIdRouteImport
      parentRoute: typeof ReadRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$chapterId/': {
      id: '/read/$chapterId/'
      path: '/'
      fullPath: '/read/$chapterId/'
      preLoaderRoute: typeof ReadChapterIdIndexRouteImport
      parentRoute: typeof ReadChapterIdRoute
    }
    '/read/$chapterId/$sectionId': {
      id: '/read/$chapterId/$sectionId'
      path: '/$sectionId'
      fullPath: '/read/$chapterId/$sectionId'
      preLoaderRoute: typeof ReadChapterIdSectionIdRouteImport
      parentRoute: typeof ReadChapterIdRoute
    }
  }
}

interface ReadChapterIdRouteChildren {
  ReadChapterIdSectionIdRoute: typeof ReadChapterIdSectionIdRoute
  ReadChapterIdIndexRoute: typeof ReadChapterIdIndexRoute
}

const ReadChapterIdRouteChildren: ReadChapterIdRouteChildren = {
  ReadChapterIdSectionIdRoute: ReadChapterIdSectionIdRoute,
  ReadChapterIdIndexRoute: ReadChapterIdIndexRoute,
}

const ReadChapterIdRouteWithChildren = ReadChapterIdRoute._addFileChildren(
  ReadChapterIdRouteChildren,
)

interface ReadRouteChildren {
  ReadChapterIdRoute: typeof ReadChapterIdRouteWithChildren
  ReadIndexRoute: typeof ReadIndexRoute
}

const ReadRouteChildren: ReadRouteChildren = {
  ReadChapterIdRoute: ReadChapterIdRouteWithChildren,
  ReadIndexRoute: ReadIndexRoute,
}

const ReadRouteWithChildren = ReadRoute._addFileChildren(ReadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  ReadRoute: ReadRouteWithChildren,
  TestRoute: TestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
